
export default new Map([
["src/content/docs/customization/configuration.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcustomization%2Fconfiguration.mdx&astroContentModuleFlag=true")],
["src/content/docs/customization/themes.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcustomization%2Fthemes.mdx&astroContentModuleFlag=true")],
["src/content/docs/reference/ai-integration.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Freference%2Fai-integration.mdx&astroContentModuleFlag=true")],
["src/content/docs/reference/api-reference.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Freference%2Fapi-reference.mdx&astroContentModuleFlag=true")],
["src/content/docs/reference/faq.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Freference%2Ffaq.mdx&astroContentModuleFlag=true")],
["src/content/docs/features/calendar.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Ffeatures%2Fcalendar.mdx&astroContentModuleFlag=true")],
["src/content/docs/reference/contributing.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Freference%2Fcontributing.mdx&astroContentModuleFlag=true")],
["src/content/docs/features/chores.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Ffeatures%2Fchores.mdx&astroContentModuleFlag=true")],
["src/content/docs/features/dashboard.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Ffeatures%2Fdashboard.mdx&astroContentModuleFlag=true")],
["src/content/docs/features/family.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Ffeatures%2Ffamily.mdx&astroContentModuleFlag=true")],
["src/content/docs/features/grocery.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Ffeatures%2Fgrocery.mdx&astroContentModuleFlag=true")],
["src/content/docs/features/notifications.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Ffeatures%2Fnotifications.mdx&astroContentModuleFlag=true")],
["src/content/docs/features/photos.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Ffeatures%2Fphotos.mdx&astroContentModuleFlag=true")],
["src/content/docs/features/music.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Ffeatures%2Fmusic.mdx&astroContentModuleFlag=true")],
["src/content/docs/features/screensaver.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Ffeatures%2Fscreensaver.mdx&astroContentModuleFlag=true")],
["src/content/docs/getting-started/installation.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fgetting-started%2Finstallation.mdx&astroContentModuleFlag=true")],
["src/content/docs/getting-started/deployment.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fgetting-started%2Fdeployment.mdx&astroContentModuleFlag=true")],
["src/content/docs/features/timer.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Ffeatures%2Ftimer.mdx&astroContentModuleFlag=true")],
["src/content/docs/getting-started/walkthrough.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fgetting-started%2Fwalkthrough.mdx&astroContentModuleFlag=true")],
["src/content/docs/getting-started/welcome.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fgetting-started%2Fwelcome.mdx&astroContentModuleFlag=true")]]);
		